export default function DefaultTags() {
  return (
    <>
      <meta charSet="utf-8" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta name="theme-color" content="#000" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
