import DefaultTags from "./DefaultTags";

export default function Head({ params }: { params: { slug: string } }) {
  return (
    <>
      <link rel="preconnect" href="https://products-nextjs.vercel.app" />
      <DefaultTags />
      <title>Next App</title>
      <meta name="description" content="Generated by create next app" />
    </>
  );
}
